# scripts/chapterX/ 配下に差分がある PR へ章ラベルを付与する設定
chapter2:
  - changed-files:
      - any-glob-to-any-file: 'scripts/chapter2/**'
chapter3:
  - changed-files:
      - any-glob-to-any-file: 'scripts/chapter3/**'
chapter4:
  - changed-files:
      - any-glob-to-any-file: 'scripts/chapter4/**'
chapter5:
  - changed-files:
      - any-glob-to-any-file: 'scripts/chapter5/**'
chapter6:
  - changed-files:
      - any-glob-to-any-file: 'scripts/chapter6/**'
chapter7:
  - changed-files:
      - any-glob-to-any-file: 'scripts/chapter7/**'
