# scripts/chapterX/ 配下に差分がある PR へ章ラベルを付与する設定
chapter2:
  - scripts/chapter2/**
chapter3:
  - scripts/chapter3/**
chapter4:
  - scripts/chapter4/**
chapter5:
  - scripts/chapter5/**
chapter6:
  - scripts/chapter6/**
chapter7:
  - scripts/chapter7/**
